version: "2"

services:
  web:
    build: .
    ports:
      - 9000:9000
    depends_on:
      - mongo
    networks:
      - back-tier
      - front-tier

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
